version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:11.9.0-browsers'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - sandbox/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
